### ISSUE TITLE
Saving the whole image

### ISSUE THREAD

**Issue by joebayles** [kjellmf/military-symbology-explorer#10]
In the Symbol Set browser, as a symbol is created on the left, add the ability to save the complete symbol, as opposed to the top layer.

Also for the crafted image in the Symbol Identification Code Explorer.

**Comment by kjellmf** [comment]
Does "save the complete symbol" mean saving it as an image/SVG?

**Comment by joebayles** [comment]
Yes, as an image.

**Comment by kjellmf** [comment]
Ok. The symbol explorer is a client side javascript application, so saving it as an image may not be straightforward. The reason you only can save the top layer is because the symbol is created by overlaying several separate images/SVGs. 

I will investigate and try to find a workaround. It is a good opportunity for learning more about new HTML5 APIs

**Comment by kjellmf** [comment]
This looks promising http://techslides.com/save-svg-as-an-image I will experiment with this approach.

**Comment by joebayles** [comment]
:+1:

**Comment by kjellmf** [comment]
I have found a solution that works in Chrome (and probably FF and Safari). I'm struggling with Internet Explorer 11. Apparently IE has a security model that does not allow saving a `Canvas` after you draw an SVG graphic on it.  I'm still investigating.

**Comment by kjellmf** [comment]
Added "Save as PNG" in symbol explorer in 75f16571dab6aac08231ef6535ebfa544b918cd3. Does not work in IE. I'm not satisfied with the implementation yet. 

Any thoughts on the UI @joebayles ? Should the file name be the SIC?

**Comment by kjellmf** [comment]
One possible workaround for IE is to use the [Canvg](https://github.com/gabelerner/canvg) library as described here http://willkoehler.net/2014/11/07/client-side-solution-for-downloading-highcharts-charts-as-images.html. It is a large library, so I don't know if I want to use it.

**Comment by joebayles** [comment]
Agreed, complete SIC should be the file name. Any other implementation would be too long. As far as what it should look like, add buttons to reset the image (start over), and save the image.

**Comment by kjellmf** [comment]
Closing this since the functionality is implemented. Track IE-issue in #40
