### ISSUE TITLE
Implement LimitUseTo

### ISSUE THREAD

**Issue by abouffard** [kjellmf/military-symbology-explorer#12]
See, @kjellmf , see what you've opened yourself up to?!?  ;-)

Great job!  Thanks for building this project.  It helps demonstrate the usefulness of JMSML and helps validate all the hard work we put into building it.

My suggestion to you is that you implement the LimitUseTo attributes on modifier.  The test case here would be to restrict the user's ability to select the Boom, Drogue, and Boom and Drogue sector two air modifiers when working with any Air icons other that Tanker.  There are some other examples of these restrictions in JMSML.

More limits are coming in the future, in 2525D Change 1 and APP-6(D).

**Comment by kjellmf** [comment]
Thank you @abouffard  for your kind words and thank you for making the symbol data available!

I have overlooked the LimitUseTo feature in the schema. Excellent suggestion! I will implement support for this soon.

**Comment by kjellmf** [comment]
@abouffard Does the `LimitUseTo` also apply to entity sub types of the referenced element?  

Example:
`<Modifier ID="AUXILIARY_MOD" Label="Auxiliary" Graphic="35021.svg" Category="Mission Area" LimitUseTo="SUBMARINE">`

Is this modifier also valid for the entity sub types `SUBMARINE_SURFACED, SUBMARINE_SNORKELING, SUBMARINE_BOTTOMED` ?

**Comment by abouffard** [comment]
Yes, that is a reasonable assumption.

If a given modifier applies to some entity subtypes but not all sibling subtypes, then LimitUseTo has to have a space delimited list of IDs for the specific subtypes it can be used with.

**Comment by kjellmf** [comment]
Implemented in 98a69eb10aa7f5e68342e74a14acabe8b11ef509. To keep things simple I first check for `EntitySubType` in `LimitUseTo`, then `EntityType` and then `Entity`. This is different from the logic you described @abouffard . I will change the logic in my code later.
