### ISSUE TITLE
Disable drawing of echelon, status etc. for control measures

### ISSUE THREAD

**Issue by kjellmf** [kjellmf/military-symbology-explorer#21]
Currently, in the symbol explorer, you can display control measures with echelon indicators, status etc. This does not make sense. Irrelevant fields should be disabled.

**Comment by csmoore** [comment]
Note: for control measures, a Status / Operational Condition attribute could eventually be used to dash the lines. Not sure how you would do this with the SVGs (unless you replaced the line styles), but just something to think about.

![image](https://cloud.githubusercontent.com/assets/3090809/6391892/3475130c-bd89-11e4-9496-f07e099aabf0.png)

**Comment by kjellmf** [comment]
You are right about the status field. Unfortunately there are no "planned versions" of every control measures in the SVGs. You have several "planned versions" in the symbol set data though. For example Maneuver Areas - Area - Planned - Friendly planned, Minefield - Planned etc. Manipulating line styles is an option. Thanks for the tip.

**Comment by kjellmf** [comment]
Renamed the issue. It actually makes sense to provide both a status and echelon for a control measure. I should, however, not draw them.
