### ISSUE TITLE
Invisible Frame for Planned Status with Pending/Anticipated/Suspect Affiliations

### ISSUE THREAD

**Issue by csmoore** [kjellmf/military-symbology-explorer#24]
This web app looks really good on an iPad.

The only thing I noticed in a quick test were some minor issues with boundary conditions such as this.

For affiliations of Pending/Anticipated/Suspect, you unfortunately have to ignore the Status/Operational Condition of "Planned" (or the frame won't show up)

![image](https://cloud.githubusercontent.com/assets/3090809/6392033/63efe214-bd8a-11e4-8294-4e5b655f0be5.png)

Also very minor, this one button was cut off:
![image](https://cloud.githubusercontent.com/assets/3090809/6392063/afd17026-bd8a-11e4-829c-421a50aad6c8.png)

**Comment by kjellmf** [comment]
Thanks for the reporting this. I'll look into it. 

The explorer currently has some issues on smaller screen sizes. I have plans for improving this. See issue #19

**Comment by kjellmf** [comment]
@csmoore The problem is that JMSML does not specify a `PlannedGraphic` for any of the affiliations with `StandardIdentityID="SI_PENDING"` ([example](https://github.com/Esri/joint-military-symbology-xml/blob/6f6c675a725b7589e9a8aaf22fcb520205222b35/instance/jmsml_D_Base.xml#L868)). Is this by design?

**Comment by csmoore** [comment]
Not sure, it is definitely a conflict in the standard - do you show X (a dot frame) or Y (a dash frame) if both conditions are met. Fortunately or unfortunately at a realistic size (32 points) you can't tell the difference - but you definitely notice a missing frame.

But for this issue, is it possible to fall back to "Graphic" if a PlannedGraphic/CivilianGraphic attribute doesn't exist.

**Comment by kjellmf** [comment]
I have now implemented a fall back to `Graphic`. Thanks again for the bug report.
