### ISSUE TITLE
Link directly to a symbol in symbol explorer

### ISSUE THREAD

**Issue by kjellmf** [kjellmf/military-symbology-explorer#25]
Make it possible to show a symbol directly using a parameter (SIC) in the url.

**Comment by csmoore** [comment]
That is pretty cool and extremely useful for testing - nice work:

Ex: http://kjellmf.github.io/military-symbology-explorer/#/explore/10041010111213030000

**Comment by kjellmf** [comment]
Thanks. I see that you already have used the linking functionality in one of the JMSML issues. Reminds me that I should check that the SVGs are in sync with the JMSML repo. 

It should also be possible to link to a symbol from the symbol set browser, so I have added issue #26 to track this.

**Comment by kjellmf** [comment]
SVGs are in sync now (40c4e5cf82e18f4f082eb22fff94920e94a4da23)
