### ISSUE TITLE
Show special entity subtypes

### ISSUE THREAD

**Issue by kjellmf** [kjellmf/military-symbology-explorer#29]
Some land unit icons may use special entity subtypes. Need to figure out how to show them.  
![image](https://cloud.githubusercontent.com/assets/29217/6471609/d208e834-c1ec-11e4-9373-8409d28508be.png)

**Comment by csmoore** [comment]
That is a bit of a special case, here is an example in case it helps:

100**3**1000001110**98**0000

Add layer:
Appendices\Land\10xxxx**98**_**1**.svg

![sampleimage](https://cloud.githubusercontent.com/assets/3090809/6472265/18a51cfa-c1bf-11e4-884a-761c38be40f7.png)

You may want to handle it like a special "Modifier 3" (& I wish that is how the specification had done it as well for clarity)

**Comment by kjellmf** [comment]
Thanks for the example. Really helpful. I could not find many details in the standard.  So the special entity subtypes can basically be applied to every land unit entity type? Then it makes sense to implement it as a modifier.

**Comment by csmoore** [comment]
The standard (Table D-V) currently says it applies to "**some** entity types" so I did interpret that as "all" since it had no other guidance.

But I **think** the intention was that it could only apply if the last 2 digits of entity code were "00" ex in the example above "111000"
