### ISSUE TITLE
No Frame for Sea Surface/Ownship Symbol

### ISSUE THREAD

**Issue by csmoore** [kjellmf/military-symbology-explorer#30]
This is another odd/special case - this symbol doesn't have a frame (it would actually be more consistent if this symbol was moved into Control Measures symbol set in the standard for this reason)

http://kjellmf.github.io/military-symbology-explorer/#/explore/10043000001500000000

http://kjellmf.github.io/military-symbology-explorer/#/explore/10033000001500000000

**Comment by kjellmf** [comment]
I could add a check for handling this symbol, but this special case should also be reflected in the JMSML schema. Maybe by giving it a special icon type, `Icon=NO_FRAME`? I will create an issue for this on the JMSML repo.

**Comment by kjellmf** [comment]
Closed by 816c28e
Example http://explorer.milsymb.net/#/explore/10033000001500000000

**Comment by kjellmf** [comment]
Created issue https://github.com/Esri/joint-military-symbology-xml/issues/177
