### ISSUE TITLE
Typo in Icon description for Entity selected items

### ISSUE THREAD

**Issue by yemikudaisi** [kjellmf/military-symbology-explorer#46]
The icon description displayed when you select specific items in the Entity select control contains a typo, particularly, the spelling of **hierarchical** is wrong.

Here is what is displayed when you select "_Movement and Maneuver_" or "_Fires_":

> No icon is associated with this entity. It is for hiearchical purposes only.

**Comment by kjellmf** [comment]
Thank you for the bug report. The typo originally comes from the [Esri/joint-military-symbology-xml](https://github.com/Esri/joint-military-symbology-xml) project. It looks that they still have a few of them (https://github.com/Esri/joint-military-symbology-xml/search?l=XML&q=hiearchical) in the code base.

I will fix the typo the next time I update the project.

**Comment by yemikudaisi** [comment]
Do I report the issue there, or you'll do it ?

**Comment by kjellmf** [comment]
I have created a pull request https://github.com/Esri/joint-military-symbology-xml/pull/528 that fixes the typos.
